#pragma once
#include <iostream>
#include <vector>
#include <stdexcept>
#include "common.h"

/**
 * The Virtual Machine executes the bytecode generated by the compiler.
 * It uses a stack for temporary math and a 'globals' vector for variable storage.
 */
class stackVM
{
private:
    std::vector<int> stack;     // Temporary workspace for math
    std::vector<int> program;   // The array of instructions to execute
    std::vector<int> globals;   // Memory for variables (addressed by ID)
    size_t ip = 0;              // Instruction Pointer: tells us which command is next

public:
    // Prepare the VM with a new program and reset state
    void loadprogram(const std::vector<int> &prog)
    {
        program = prog;
        ip = 0;
        globals.assign(100, 0); // Pre-allocate space for 100 variables
        stack.clear();
    }

    // The main execution loop
    void run()
    {
        bool running = true;
        while(running && ip < program.size())
        {
            int instr = program[ip++];

            switch(static_cast<opcode>(instr))
            {
                // PUSH <value>: Add a number to the stack
                case opcode::push:
                {
                    stack.push_back(program[ip++]);
                    break;
                }
                // ADD: Pop two, add them, push result
                case opcode::add:
                {
                    int b = stack.back(); stack.pop_back();
                    int a = stack.back(); stack.pop_back();
                    stack.push_back(a + b);
                    break;
                }
                // SUB: Pop two, subtract (a-b), push result
                case opcode::sub:
                {
                    int b = stack.back(); stack.pop_back();
                    int a = stack.back(); stack.pop_back();
                    stack.push_back(a - b);
                    break;
                }
                // MUL: Pop two, multiply, push result
                case opcode::mul:
                {
                    int b = stack.back(); stack.pop_back();
                    int a = stack.back(); stack.pop_back();
                    stack.push_back(a * b);
                    break;
                }
                // DIV: Pop two, divide (a/b), push result
                case opcode::div:
                {
                    int b = stack.back(); stack.pop_back();
                    int a = stack.back(); stack.pop_back();
                    if(b == 0) throw std::runtime_error("Division by zero");
                    stack.push_back(a / b);
                    break;
                }
                // LESS: a < b
                case opcode::less:
                {
                    int b = stack.back(); stack.pop_back();
                    int a = stack.back(); stack.pop_back();
                    stack.push_back(a < b ? 1 : 0);
                    break;
                }
                // EQUAL: a == b
                case opcode::equal:
                {
                    int b = stack.back(); stack.pop_back();
                    int a = stack.back(); stack.pop_back();
                    stack.push_back(a == b ? 1 : 0);
                    break;
                }
                // JUMP <target>: Set IP to target
                case opcode::jump:
                {
                    ip = program[ip]; // Target address is stored at current IP
                    break;
                }
                // JUMP_IF_FALSE <target>: Jump if top of stack is 0
                case opcode::jump_if_false:
                {
                    int target = program[ip++];
                    int cond = stack.back(); stack.pop_back();
                    if (cond == 0) ip = target;
                    break;
                }
                // SET_GLOBAL <id>: Pop from stack and save to globals[id]
                case opcode::set_global:
                {
                    int var_id = program[ip++]; 
                    int val = stack.back(); stack.pop_back();           
                    globals[var_id] = val;    
                    break;
                }
                // GET_GLOBAL <id>: Read globals[id] and push to stack
                case opcode::get_global:
                {
                    int var_id = program[ip++]; 
                    stack.push_back(globals[var_id]);      
                    break;
                }
                // PRINT: Pop from stack and display to console
                case opcode::print:
                {
                    std::cout << "output: " << stack.back() << std::endl;
                    stack.pop_back();   
                    break;
                }
                // HALT: Stop the VM
                case opcode::halt:
                {
                    running = false;
                    break;
                }
            }
        }
    }
};
